package com.dongtech.bean;

import java.io.Serializable;

public class PermissionInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissioninfo.id
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissioninfo.permissionnum
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    private String permissionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissioninfo.permissionexplain
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    private String permissionexplain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissioninfo.id
     *
     * @return the value of permissioninfo.id
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissioninfo.id
     *
     * @param id the value for permissioninfo.id
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissioninfo.permissionnum
     *
     * @return the value of permissioninfo.permissionnum
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    public String getPermissionnum() {
        return permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissioninfo.permissionnum
     *
     * @param permissionnum the value for permissioninfo.permissionnum
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    public void setPermissionnum(String permissionnum) {
        this.permissionnum = permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissioninfo.permissionexplain
     *
     * @return the value of permissioninfo.permissionexplain
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    public String getPermissionexplain() {
        return permissionexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissioninfo.permissionexplain
     *
     * @param permissionexplain the value for permissioninfo.permissionexplain
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    public void setPermissionexplain(String permissionexplain) {
        this.permissionexplain = permissionexplain;
    }
}