package com.dongtech.bean;

import java.io.Serializable;

public class PermissionPath implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionpath.id
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionpath.permissionnum
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    private String permissionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionpath.permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    private String permissionpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionpath.id
     *
     * @return the value of permissionpath.id
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionpath.id
     *
     * @param id the value for permissionpath.id
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionpath.permissionnum
     *
     * @return the value of permissionpath.permissionnum
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    public String getPermissionnum() {
        return permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionpath.permissionnum
     *
     * @param permissionnum the value for permissionpath.permissionnum
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    public void setPermissionnum(String permissionnum) {
        this.permissionnum = permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionpath.permissionpath
     *
     * @return the value of permissionpath.permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    public String getPermissionpath() {
        return permissionpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionpath.permissionpath
     *
     * @param permissionpath the value for permissionpath.permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    public void setPermissionpath(String permissionpath) {
        this.permissionpath = permissionpath;
    }
}