package com.dongtech.bean;

import java.io.Serializable;

public class PermissionInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissioninfo.id
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissioninfo.permissionnum
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    private Integer permissionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissioninfo.permissionexplain
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    private String permissionexplain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissioninfo.id
     *
     * @return the value of permissioninfo.id
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissioninfo.id
     *
     * @param id the value for permissioninfo.id
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissioninfo.permissionnum
     *
     * @return the value of permissioninfo.permissionnum
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    public Integer getPermissionnum() {
        return permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissioninfo.permissionnum
     *
     * @param permissionnum the value for permissioninfo.permissionnum
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    public void setPermissionnum(Integer permissionnum) {
        this.permissionnum = permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissioninfo.permissionexplain
     *
     * @return the value of permissioninfo.permissionexplain
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    public String getPermissionexplain() {
        return permissionexplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissioninfo.permissionexplain
     *
     * @param permissionexplain the value for permissioninfo.permissionexplain
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    public void setPermissionexplain(String permissionexplain) {
        this.permissionexplain = permissionexplain;
    }
}