package com.dongtech.bean;

import java.io.Serializable;

public class PermissionPath implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionpath.id
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionpath.permissionnum
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    private Integer permissionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissionpath.permissionpath
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    private String permissionpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionpath.id
     *
     * @return the value of permissionpath.id
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionpath.id
     *
     * @param id the value for permissionpath.id
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionpath.permissionnum
     *
     * @return the value of permissionpath.permissionnum
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    public Integer getPermissionnum() {
        return permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionpath.permissionnum
     *
     * @param permissionnum the value for permissionpath.permissionnum
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    public void setPermissionnum(Integer permissionnum) {
        this.permissionnum = permissionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissionpath.permissionpath
     *
     * @return the value of permissionpath.permissionpath
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    public String getPermissionpath() {
        return permissionpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissionpath.permissionpath
     *
     * @param permissionpath the value for permissionpath.permissionpath
     *
     * @mbggenerated Fri Aug 03 15:49:22 CST 2018
     */
    public void setPermissionpath(String permissionpath) {
        this.permissionpath = permissionpath;
    }
}