package com.dongtech.bean;

import java.io.Serializable;

public class UserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.id
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.userid
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.permissonid
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    private Integer permissonid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.id
     *
     * @return the value of userrole.id
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.id
     *
     * @param id the value for userrole.id
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.userid
     *
     * @return the value of userrole.userid
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.userid
     *
     * @param userid the value for userrole.userid
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.permissonid
     *
     * @return the value of userrole.permissonid
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    public Integer getPermissonid() {
        return permissonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.permissonid
     *
     * @param permissonid the value for userrole.permissonid
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    public void setPermissonid(Integer permissonid) {
        this.permissonid = permissonid;
    }
}