package com.dongtech.bean;

public class UserProfile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userprofile.id
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userprofile.userid
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userprofile.useraddress
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    private String useraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userprofile.age
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userprofile.aboutuser
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    private String aboutuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userprofile.id
     *
     * @return the value of userprofile.id
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userprofile.id
     *
     * @param id the value for userprofile.id
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userprofile.userid
     *
     * @return the value of userprofile.userid
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userprofile.userid
     *
     * @param userid the value for userprofile.userid
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userprofile.useraddress
     *
     * @return the value of userprofile.useraddress
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userprofile.useraddress
     *
     * @param useraddress the value for userprofile.useraddress
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userprofile.age
     *
     * @return the value of userprofile.age
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userprofile.age
     *
     * @param age the value for userprofile.age
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userprofile.aboutuser
     *
     * @return the value of userprofile.aboutuser
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public String getAboutuser() {
        return aboutuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userprofile.aboutuser
     *
     * @param aboutuser the value for userprofile.aboutuser
     *
     * @mbggenerated Fri Aug 03 15:54:36 CST 2018
     */
    public void setAboutuser(String aboutuser) {
        this.aboutuser = aboutuser;
    }
}