package com.dongtech.bean;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.worktime
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    private String worktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.workstatus
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    private String workstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.worktime
     *
     * @return the value of userinfo.worktime
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public String getWorktime() {
        return worktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.worktime
     *
     * @param worktime the value for userinfo.worktime
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public void setWorktime(String worktime) {
        this.worktime = worktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.workstatus
     *
     * @return the value of userinfo.workstatus
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public String getWorkstatus() {
        return workstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.workstatus
     *
     * @param workstatus the value for userinfo.workstatus
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public void setWorkstatus(String workstatus) {
        this.workstatus = workstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbggenerated Thu Aug 02 14:16:45 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }
}