package com.dongtech.bean;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.id
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.userid
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userrole.permissonid
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    private String permissonid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.id
     *
     * @return the value of userrole.id
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.id
     *
     * @param id the value for userrole.id
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.userid
     *
     * @return the value of userrole.userid
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.userid
     *
     * @param userid the value for userrole.userid
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userrole.permissonid
     *
     * @return the value of userrole.permissonid
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    public String getPermissonid() {
        return permissonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userrole.permissonid
     *
     * @param permissonid the value for userrole.permissonid
     *
     * @mbggenerated Thu Aug 02 14:17:25 CST 2018
     */
    public void setPermissonid(String permissonid) {
        this.permissonid = permissonid;
    }
}