package com.dongtech.mapper;

import com.dongtech.bean.PermissionPath;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PermissionPathMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    int insert(PermissionPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    int insertSelective(PermissionPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    PermissionPath selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    int updateByPrimaryKeySelective(PermissionPath record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissionpath
     *
     * @mbggenerated Thu Aug 02 14:16:17 CST 2018
     */
    int updateByPrimaryKey(PermissionPath record);
}