package com.dongtech.mapper;

import com.dongtech.bean.PermissionInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface PermissionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    int insert(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    int insertSelective(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    PermissionInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    int updateByPrimaryKeySelective(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Fri Aug 03 15:48:39 CST 2018
     */
    int updateByPrimaryKey(PermissionInfo record);

    /**
     * 查询所有角色信息
     * @return
     */
    List<PermissionInfo> selectAllPermission();
}