package com.dongtech.mapper;

import com.dongtech.bean.PermissionInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PermissionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    int insert(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    int insertSelective(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    PermissionInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    int updateByPrimaryKeySelective(PermissionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissioninfo
     *
     * @mbggenerated Thu Aug 02 14:15:11 CST 2018
     */
    int updateByPrimaryKey(PermissionInfo record);
}