package com.dongtech.mapper;

import com.dongtech.bean.UserInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 03 14:32:13 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 03 14:32:13 CST 2018
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 03 14:32:13 CST 2018
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 03 14:32:13 CST 2018
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 03 14:32:13 CST 2018
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Fri Aug 03 14:32:13 CST 2018
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 根据用户名查询用户信息
     * @param map
     * @return
     */
    UserInfo selectByUsername(Map<String,Object> map);

    /**
     * 查询所有用户信息
     * @return
     */
    List<UserInfo> selectAllUser();

    /**
     * 根据用户名和密码查询用户
     * @param map
     * @return
     */
    UserInfo selectByUsernameAndPassword(Map<String,Object> map);
}