package com.dongtech.mapper;

import com.dongtech.bean.UserRole;
import org.apache.ibatis.annotations.Mapper;

import java.util.Map;

@Mapper
public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    UserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userrole
     *
     * @mbggenerated Fri Aug 03 15:50:08 CST 2018
     */
    int updateByPrimaryKey(UserRole record);

    /**
     * 根据用户名查询用户个人信息
     * @param username
     * @return
     */
    Map<String,Object> selectUserProfileByUserName(String username);
}