package com.dongtech.mapper;

import com.dongtech.bean.UserInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.Map;
@Mapper
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Thu Aug 02 15:45:48 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Thu Aug 02 15:45:48 CST 2018
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Thu Aug 02 15:45:48 CST 2018
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Thu Aug 02 15:45:48 CST 2018
     */
    UserInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Thu Aug 02 15:45:48 CST 2018
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbggenerated Thu Aug 02 15:45:48 CST 2018
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 根据用户名和密码查询用户
     * @param map
     * @return
     */
    UserInfo selectByUsernameAndPassword(Map<String,Object> map);

    /**
     * 根据用户名查询用户信息
     * @param map
     * @return
     */
    UserInfo selectByUsername(Map<String,Object> map);
}